### ISSUE TITLE
Issue reading the BOOL tags

### ISSUE THREAD

**Issue by ashpatell** [TheFern2/clx.libplctag.NET#1]
I'm having that issue reading the BOOL tags.

var result = await myPLC.Read("testBool", TagType.Bool).ConfigureAwait(false);
var result1 = await myPLC.ReadTag<BoolPlcMapper, bool>("testBool");

i tested both of this but still unable to get the value from PLC

**Comment by TheFern2** [comment]
Hi there, this library is unittested before release. Every single type has a unittest and [tests](https://github.com/TheFern2/clx.libplctag.NET/blob/main/clx.libplctag.NET.Tests/WriteReadTags.cs) read and write. All tests passed for current release.

![image](https://user-images.githubusercontent.com/10265682/192352015-4b161b8d-d7d2-40bf-99d1-17eb103b620b.png)

- Please share all code, how are you instantiating myPLC? 
- PLC model? 
- Console result and result1, share results.
- Are you able to read other types?

**Comment by ashpatell** [comment]
var resultBool = await myPLC.Read("Test_BOOL", TagType.Bool).ConfigureAwait(false);
            Console.WriteLine(resultBool);

            var resultDINT = await myPLC.Read("Test_DINT", TagType.Dint).ConfigureAwait(false);
            Console.WriteLine(resultDINT);

            var resultINT = await myPLC.Read("Test_INT", TagType.Int).ConfigureAwait(false);
            Console.WriteLine(resultINT);`

**Comment by ashpatell** [comment]
var myPLC = new PLC("192.168.0.2");

            var resultBool = await myPLC.Read("Test_BOOL", TagType.Bool).ConfigureAwait(false);
            Console.WriteLine(resultBool);

            var resultDINT = await myPLC.Read("Test_DINT", TagType.Dint).ConfigureAwait(false);
            Console.WriteLine(resultDINT);

            var resultINT = await myPLC.Read("Test_INT", TagType.Int).ConfigureAwait(false);
            Console.WriteLine(resultINT);`

This is code I used. I use [clx.libplctag.NET.TestProgram] to test it. 
So far i'm able to read INT and DINT just fine but BOOL tag always returns False.

![image](https://user-images.githubusercontent.com/29357117/192418602-43a789be-f209-4f87-8e17-c23cdf00c250.png)
![image](https://user-images.githubusercontent.com/29357117/192418784-1349b09b-2e0d-463b-8987-fde293693007.png)
![image](https://user-images.githubusercontent.com/29357117/192418852-402b054a-721d-47f2-baba-74467436cf1e.png)

**Comment by ashpatell** [comment]
![image](https://user-images.githubusercontent.com/29357117/192419207-46c76fe4-ebce-4bf0-b135-f6ae1c103b40.png)

**Comment by TheFern2** [comment]
That's really strange, we've been using this library internally in production for 2 years without any issues. I do remember at some point someone saying libplctag core had issues with booleans but this is using a stable libplctag version. You didn't manually upgrade libplctag?

A few more questions:

- which netcore version are you using? 
- have you tried creating a netcore project, then adding clx.libplctag.NET with nugget package manager, does that make a difference?
- are you 100% your bool tag is writable, manually set to false in the plc, then try writing true with library, can you the write to it?
- can you try to do one read, exit project, change bool in plc, do one read, does it work for true or false?

```csharp
var myPLC = new PLC("192.168.1.14", 1);
            
var resultBool = await myPLC.Read("BaseBOOL", TagType.Bool).ConfigureAwait(false);
Console.WriteLine(resultBool);

var writeBool = await myPLC.Write("BaseBOOL", TagType.Bool, true);
Console.WriteLine(writeBool);

resultBool = await myPLC.Read("BaseBOOL", TagType.Bool).ConfigureAwait(false);
Console.WriteLine(resultBool);

writeBool = await myPLC.Write("BaseBOOL", TagType.Bool, false);
Console.WriteLine(writeBool);

resultBool = await myPLC.Read("BaseBOOL", TagType.Bool).ConfigureAwait(false);
Console.WriteLine(resultBool);

resultBool = await myPLC.Read("BaseBOOLxxxdddd", TagType.Bool).ConfigureAwait(false);
Console.WriteLine(resultBool);

[snip]program/bin/Debug/netcoreapp3.1/clx.libplctag.NET.TestProgram.exe
Response: BaseBOOL False Success
Response: BaseBOOL  Success
Response: BaseBOOL True Success
Response: BaseBOOL  Success
Response: BaseBOOL False Success
Response: BaseBOOLxxxdddd  ErrorNotFound

```

**Comment by TheFern2** [comment]
@dmroeder @kyle-github compactlogix should behave the same for booleans, right?

**Comment by TheFern2** [comment]
Closing due to no response. Feel free to reopen if you still experience issues with bools, I can't find any issues on my end.

**Comment by TheFern2** [comment]
Probably a bit late but I believe the issue is now resolved, the issue was in the main wrapper and a bugfix implemented in the latest release.

https://github.com/TheFern2/clx.libplctag.NET/issues/2#issuecomment-1858745378
