### ISSUE TITLE
Boolean Read Not Working 

### ISSUE THREAD

**Issue by drpancake909** [TheFern2/clx.libplctag.NET#2]
For some reason reading a boolean tag always returns FALSE for me. I can write to the tag and in the PLC I see the value change as expected. But myTag.Read() always results with myTag.Value equaling FALSE.

**Comment by TheFern2** [comment]
Hi @drpancake909 please share your code, the library is ran through a battery of tests which do both read and write on all data types all tests passed when making a release. The library works, so either your code has a bug, or there is a tag permission set to read only in your plc.

Screenshot of tests successfully passing.
https://github.com/TheFern2/clx.libplctag.NET/issues/1#issuecomment-1258443777

**Comment by drpancake909** [comment]
hi there! thanks for reply ! sure, i saw your other instructions i follow it but i dont know what i am doing wrong. 
using clx.libplctag.NET;

var myPLC = new PLC("172.16.31.2", 0);

// Read the initial value of the new tag
var initialRead = await myPLC.Read("test_bool_plc", TagType.Bool);
Console.WriteLine(initialRead);
Console.WriteLine($"Initial Read: test_bool_plc is {initialRead.Value}");

// Write 'true' to the new tag
var writeTrueResult = await myPLC.Write("test_bool_plc", TagType.Bool, true);
Console.WriteLine(writeTrueResult);

// Read the value after writing 'true'
var readAfterWriteTrue = await myPLC.Read("test_bool_plc", TagType.Bool);
Console.WriteLine(readAfterWriteTrue);
Console.WriteLine($"Read After Write True: test_bool_plc is {readAfterWriteTrue.Value}");

// Write 'false' to the new tag
var writeFalseResult = await myPLC.Write("test_bool_plc", TagType.Bool, false);
Console.WriteLine(writeFalseResult);

// Read the value after writing 'false'
var readAfterWriteFalse = await myPLC.Read("test_bool_plc", TagType.Bool);
Console.WriteLine(readAfterWriteFalse);
Console.WriteLine($"Read After Write False: test_bool_plc is {readAfterWriteFalse.Value}");

but then this is the reply 
Response: test_bool_plc False Success
Initial Read: test_bool_plc is False
Response: test_bool_plc  Success
Response: test_bool_plc False Success
Read After Write True: test_bool_plc is False
Response: test_bool_plc  Success
Response: test_bool_plc False Success
Read After Write False: test_bool_plc is False

but i am online seeing the plc tag value and initialy is 0 and i can see it change to 1 then back to 0.  later i even added a delay and same thing

**Comment by TheFern2** [comment]
what happens if you toggle the boolean to true in rslogix5k? Does it remain true? If it doesn't then something else is overriding the value, if it does, then I have no idea why is turning back to 0. The fact that it does write to 1, tells us writing is working.

**Comment by drpancake909** [comment]
i did what you said set the tag to 1 and it does not remain true. it goes from 1 to 0. but so far i am able to write bools. read/write int and dints, seems that i am stuck with reading bool. i will keep trying
Response: test_bool_plc False Success
Initial Read: test_bool_plc is False
Response: test_bool_plc  Success
Response: test_bool_plc False Success
Read After Write True: test_bool_plc is False
Response: test_bool_plc  Success
Response: test_bool_plc False Success
Read After Write False: test_bool_plc is False

**Comment by TheFern2** [comment]
> i did what you said set the tag to 1 and it does not remain true

If it does not remain true, then somewhere in your plc code is getting overridden. If you change a bit in the plc, it should remain true. A read would not change the bit.

**Comment by TheFern2** [comment]
Just to make sure we're on the same page. Are you toggling the bool tag in rslogix? and is changing on its own?

or are you saying is changing after making a single read?

**Comment by drpancake909** [comment]
I create a new tag to be sure nothing is overriding it and then try it with a value 0 and 1 (using studio 5000) the routine as is can write the tag, 0 to 1 and back to 0, or from 1 to 0 and so on. the issue i am having is to read this tag, so far i just receive 'false'

**Comment by TheFern2** [comment]
What plc model and firmware are you using?

**Comment by TheFern2** [comment]
and do you mind doing a boolean test with https://github.com/libplctag/libplctag.NET preferably 1.0.5, all my wrapper is doing is using that wrapper which in turn using libplctag c library internally.

**Comment by TheFern2** [comment]
Nvm I found the issue, there are a few things similar issues opened on the main wrapper, so that's probably an issue lingering around 2 years. Will follow up on the issue opened there next week and see if a fix was rolled out.

https://github.com/libplctag/libplctag.NET/issues/178#issue-915344191

**Comment by TheFern2** [comment]
@drpancake909 Okay a quick read at the main wrapper bool mapper it does seem like a bugfix for boolean was done in libplctag.NET 1.2.0 https://www.nuget.org/packages/libplctag/ I think the original internal problem was that some plc's returned 1 and others 255 for a true value but the bool mapper was not properly handling this.

Please try bool read and write with libplctag.NET 1.2.0 if it works lemme know and I can re up libplctag.NET from 1.0.3 to 1.2.0 on me wrapper, I won't be able to tell if the fix works because I only use softlogix and that one is already passed the unittests. So I'm relying on you for this one test.

**Comment by TheFern2** [comment]
After further thought I am 99% the issue should be resolved by merely upgrading libplctag.NET wrapper. Please try using clxx.libplctag.NET 2.0.2 to verify boolean reads are correct.

**Comment by TheFern2** [comment]
Closing ticket, if issue is not fixed let me know.
